services:
  harryfaitdutrotteurapi:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    image: harryfaitdutrotteurapi:dev
    container_name: harryfaitdutrotteurapi
    volumes:
      - ./:/app
    ports:
      - "4564:4564"