services:
  harry-potter:
    build:
      context: .
      target: dev
      dockerfile: dockerfile
    image: harry-potter:dev
    container_name: harry-potter_dev
    volumes:
      - ./:/app
    ports:
      - "3000:3000"